apiVersion: v1
kind: Pod
metadata:
  name: app-pod
spec:
  containers:
  - name: busybox-container
    image: busybox:latest
    command: ["sh", "-c", "echo APP_MODE=$APP_MODE && sleep 3600"]
    envFrom:
     - configMapRef:
        name: app-settings