apiVersion: v1
kind: Pod
metadata:
  name: db-client
spec:
  containers:
  - name: busybox-container
    image: busybox:latest
    command: ["sh", "-c", "echo Password length: ${#DB_PASSWORD} && sleep 3600"]
    env:
     - name: DB_PASSWORD
       valueFrom:
        secretKeyRef:
          name: db-credentials
          key: password