apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  containers:
  - name: nginx-pod
    image: nginx:latest
    volumeMounts:
      - name: nginx-pod-config
        mountPath: /usr/share/nginx/html/
        readOnly: true
  volumes:
    - name: nginx-pod-config
      configMap:
        name: nginx-html
        items:
          - key: index.html
            path: index.html