apiVersion: v1
kind: Pod
metadata:
  name: storage-pod
spec:
  containers:
  - name: busybox-container
    image: busybox:latest
    command: ["sh", "-c"]
    args: ["echo 'Hello from PV' > /data/test.txt && sleep 3600"]
    volumeMounts:
    - name: data-volume
      mountPath: /data
  volumes:
  - name: data-volume
    persistentVolumeClaim:
      claimName: app-storage-claim